volumes:
  database-scraper:
    driver: local

services:
  # Scraper database service
  database-scraper:
    image: postgres:latest
    ports:
      - "${DB_SCRAPER_PUBLIC_PORT}:5432"
    volumes:
      - database-scraper:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_SCRAPER_NAME}
      - POSTGRES_USER=${DB_SCRAPER_USER}
      - POSTGRES_PASSWORD=${DB_SCRAPER_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_SCRAPER_USER} -d ${DB_SCRAPER_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s