services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"   # S3 compatible API
      - "9001:9001"   # Web UI
    environment:
      MINIO_ROOT_USER: adminadmin
      MINIO_ROOT_PASSWORD: adminadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data: