// <auto-generated />
using System;
using JobSeeker.Deduplication.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobSeeker.Deduplication.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250615162056_RawVacancyCreationTracking")]
    partial class RawVacancyCreationTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobSeeker.Deduplication.Domain.Entities.RawVacancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeduplicationCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Location")
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("Occupation")
                        .HasColumnType("integer");

                    b.Property<int>("OccupationGroup")
                        .HasColumnType("integer");

                    b.Property<int?>("SkillTag")
                        .HasColumnType("integer");

                    b.Property<string>("SourceDomain")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<int?>("Specialization")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("RawVacancies");
                });
#pragma warning restore 612, 618
        }
    }
}
